#!/usr/bin/env bash
# Instal and setup haproxy

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get install haproxy=2.0.\*

echo "
frontend Local_Server
	bind *:80
	mode http
	default_backend web-backend

backend web-backend
	balance roundrobin
	server 146785-web-01 100.25.140.189:80 check
	server 146785-web-02 100.26.226.195:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
